const produtos = [
  {
    nome: "Pantera Brava Gigante ",
    preco: "R$ 3.999,00",
    imagem: "./img/panterabravaGG.jpeg",
    dimencoes: "40(A) x 60(L) x 182(C) Cm ",
    categoria: "animais",
  },
  {
    nome: "Pantera Ataque Pequena ",
    preco: "R$ 630,00",
    imagem: "./img/panteraataqueP.jpg",
    dimencoes: "16(A) x 13(L) x 71(C) Cm ",
    categoria: "animais",
  },
  {
    nome: "Pantera Caminhando Gigante ",
    preco: "R$ 5.299,00",
    imagem: "./img/panteracaminhandoGG.jpg",
    dimencoes: "88(A) x 36(L) x 175(C) Cm ",
    categoria: "animais",
  },
  {
    nome: "Leão Caminhando Gigante", 
    preco: "R$ 6.399,00",
    imagem: "./img/leaogigante.jpg",
    dimencoes: "110(A) x 60(L) x 195(C) Cm ",
    categoria: "animais",
  },
  {
    nome: "Leão Caminhando Grande", 
    preco: "R$ 4.170,00",
    imagem: "./img/leaocaminhandoM.jpg",
    dimencoes: "83(A) x 42(L) x 135(C) Cm ",
    categoria: "animais",
  },
  {
    nome: "Leão Sentado Médio",
    preco: "R$ 4.999,00",
    imagem: "./img/leaoSentadoM.png",
    dimencoes: "108(A) x 46(L) x 64(C) Cm ",
    categoria: "animais",
  },

  
  {
    nome: "Pantera Estlizada Pequena ",
    preco: "R$ 1.099,00",
    imagem: "./img/panteraEstilizadaP.png",
    dimencoes: "08(A) x 46(L) x 64(C) Cm",
    categoria: "animais",
  },
  {
    nome: "Touro Walls Stret M ",
    preco: "R$ 546,00",
    imagem: "./img/touroM.jpeg",
    dimencoes: "46(A) x 24(L) x 26(C) Cm ",
    categoria: "animais",
  },
  {
    nome: "Touro Walls Stret G ",
    preco: "R$ 1.386,00",
    imagem: "./img/touroG.jpeg",
    dimencoes: "42(A) x 82(L) x 42(C) Cm ",
    categoria: "animais",
  },
  {
    nome: "Touro Walls Stret P ",
    preco: "R$ 336,00",
    imagem: "./img/touroP.jpeg",
    dimencoes: "18(A) x 30(L) x 16(C) Cm ",
    categoria: "animais",
  },

  {
    nome: "Escultura Gorila P",
    preco: "R$ 546,00",
    imagem: "./img/gorilaP.png",
    dimencoes: "50(A) x 26(L) x 33(C) Cm ",
    categoria: "animais",
  },

  {
    nome: "Escultura Cabeça de  Cavalo Pequena",
    preco: "R$ 546,00",
    imagem: "./img/cavaloP.jpeg",
    dimencoes: "50(A) x 20(L) x 20(C) Cm ",
    categoria: "animais",
  },
  {
    nome: "Escultura Cabeça de Cavalo Média",
    preco: "R$ 1.106,00",
    imagem: "./img/cavaloM.jpeg",
    dimencoes: "74(A) x 21(L) x 21(C) Cm ",
    categoria: "animais",
  },
  {
    nome: "Escultura Cabeça de Cavalo Grande",
    preco: "R$ 2.086,00",
    imagem: "./img/cavaloG.jpeg",
    dimencoes: "105(A) x 35(L) x 35(C) Cm ",
    categoria: "animais",
  },
  {
    nome: "Escultura Buda",
    preco: "R$ 549,00",
    imagem: "./img/escultura-buda.jpeg",
    dimencoes: "52(A) x 34(L) x 20(C) Cm ",
    categoria: "esculturas",
  },

  {
    nome: "Escultura Moai Grande",
    preco: "R$ 549,00",
    imagem: "./img/escultura-moaiG.jpeg",
    dimencoes: "56(A) x 30(L) x 24(C) Cm ",
    categoria: "esculturas",
  },
  {
    nome: "Escultura Moai Média",
    preco: "R$ 448,00",
    imagem: "./img/moaiM.jpeg",
    dimencoes: "36(A) x 24(L) x 20(C) Cm ",
    categoria: "esculturas",
  },
  {
    nome: "Escultura Moai Pequena",
    preco: "R$ 224,00",
    imagem: "./img/moaiP.jpeg",
    dimencoes: "20(A) x 12(L) x 12(C) Cm ",
    categoria: "esculturas",
  },

  {
    nome: "Garrafa Caras Grande",
    preco: "R$ 275,00",
    imagem: "./img/garrafa-caras-G.jpeg",
    dimencoes: "50(A) x 13(L) x 13(C) Cm ",
    categoria: "garrafas",
  },

  {
    nome: "Garrafa Caras Média",
    preco: "R$ 264,00",
    imagem: "./img/garrafa-caras-M.jpeg",
    dimencoes: "40(A) x 12(L) x 12(C) Cm ",
    categoria: "garrafas",
  },

  {
    nome: "Garrafa Caras Pequena",
    preco: "R$ 245,00",
    imagem: "./img/garrafa-caras-P.jpeg",
    dimencoes: "30(A) x 14(L) x 14(C) Cm ",
    categoria: "garrafas",
  },

  {
    nome: "Esultura Mascara Beijo",
    preco: "R$ 449,00",
    imagem: "./img/beijo.jpg",
    dimencoes: "55(A) x 18(L) x 18(C) Cm ",
    categoria: "esculturas",
  },
  {
    nome: "Esultura Mascara Silêncio",
    preco: "R$ 449,00",
    imagem: "./img/silencio01.jpg",
    dimencoes: "55(A) x 18(L) x 18(C) Cm ",
    categoria: "esculturas",
  },

  {
    nome: "Escultura Mascara Torre Grande",
    preco: "R$ 277,00",
    imagem: "./img/Mascara Torre M.jpeg",
    dimencoes: "45(A) x 13(L) x 13(C) Cm ",
    categoria: "esculturas",
  },
  {
    nome: "Escultura Mascara Torre Média",
    preco: "R$ 245,00",
    imagem: "./img/mascaraAP.jpeg",
    dimencoes: "36(A) x 10(L) x 10(C) Cm ",
    categoria: "esculturas",
  },
  {
    nome: "Escultura Mascara Torre Pequena",
    preco: "R$ 217,00",
    imagem: "./img/mascaraTorrePP.png",
    dimencoes: "18(A)x05(L)x05(C) Cm ",
    categoria: "esculturas",
  },
  {
    nome: "Escultura Kiss",
    preco: "G= R$ 322,00 <p> P= R$238,00",
    imagem: "./img/kiss.png",
    dimencoes: "G= 40(A)x15(L)x09(C) Cm <p>P= 32(A)x13(L)x07(C) cm ",
    categoria: "esculturas",
  },

  {
    nome: "Touro Bravo",
    preco: "R$ 378,00",
    imagem: "./img/touro_bravoP.jpeg",
    dimencoes: "28(A) x 16(L) x 37(C) Cm ",
    categoria: "animais",
  },
  {
    nome: "Mascara Silêncio P",
    preco: "R$ 308,00",
    imagem: "./img/silencioP.jpeg",
    dimencoes: "35(A) x 11(L) x 11(C) Cm ",
    categoria: "esculturas",
  },
  {
    nome: "Leão Sentado P",
    preco: "R$ 1.540,00",
    imagem: "./img/leao_sentadoP.jpeg",
    dimencoes: "62(A) x 35(L) x 50(C) Cm ",
    categoria: "animais",
  },
  {
    nome: "Leão Deitado",
    preco: "R$ 1.680,00",
    imagem: "./img/leaodeitado.jpeg",
    dimencoes: "40(A) x 35(L) x 80(C) Cm ",
    categoria: "animais",
  },

  {
    nome: "Jaguar",
    preco: "R$ 2.758,00",
    imagem: "./img/jaguar.jpeg",
    dimencoes: "55(A) x 47(L) x 130(C) Cm ",
    categoria: "animais",
  },
  {
    nome: "Pantera Ataque PP",
    preco: "R$ 273,00",
    imagem: "./img/ataquepp.jpeg",
    dimencoes: "10(A) x 10(L) x 37(C) Cm ",
    categoria: "animais",
  },

  {
    nome: "Pantera Ataque M",
    preco: "R$ 1.106,00",
    imagem: "./img/ataque.jpeg",
    dimencoes: "22(A) x 17(L) x 101(C) Cm ",
    categoria: "animais",
  },

  {
    nome: "Pantera Ataque G ",
    preco: "R$ 1.946,00",
    imagem: "./img/ataque.jpeg",
    dimencoes: "32(A) x 21(L) x 150(C) Cm ",
    categoria: "animais",
  },
  {
    nome: "Pantera Ataque GG ",
    preco: "R$ 4.660,00",
    imagem: "./img/ataqueGG.jpeg",
    dimencoes: "55(A) x 40(L) x 205(C) Cm ",
    categoria: "animais",
  },

  {
    nome: "Pantera Bebendo Água M",
    preco: "R$ 1.946,00",
    imagem: "./img/bebendo-agua.jpeg",
    dimencoes: "40(A) x 40(L) x 102(C) Cm ",
    categoria: "animais",
  },
  {
    nome: "Pantera Bebendo Água  G",
    preco: "R$ 2.770,00",
    imagem: "./img/bebendoaguag.jpeg",
    dimencoes: "60(A) x 40(L) x 140(C) Cm ",
    categoria: "animais",
  },
  {
    nome: "Pantera Sentada P",
    preco: "R$ 829,00",
    imagem: "./img/pantera-sentadaP.jpeg",
    dimencoes: "64(A) x 35(L) x 26(C) Cm ",
    categoria: "animais",
  },
  {
    nome: "Pantera Sentada G",
    preco: "R$ 1.946,00",
    imagem: "./img/pantera-sentadaG.jpg",
    dimencoes: "90(A) x 44(L) x 44(C) Cm ",
    categoria: "animais",
  },
  {
    nome: "Pantera Sentada Estilizada",
    preco: "R$ 1.540,00",
    imagem: "./img/pantera-sentada.estilizada.png",
    dimencoes: "70(A)x 58(L)x 32(C) Cm ",
    categoria: "animais",
  },
  {
    nome: "Urso em pé P",
    preco: "R$ 490,00",
    imagem: "./img/urso-sentado.jpeg",
    dimencoes: "46(A) x 24(L) x 10(C) Cm ",
    categoria: "animais",
  },
  {
    nome: "Urso em pé PP",
    preco: "R$ 350,00",
    imagem: "./img/urso-sentado.jpeg",
    dimencoes: "30(A) x 18(L) x 08(C) Cm ",
    categoria: "animais",
  },
  {
    nome: "Urso Panda P",
    preco: "R$ 123,00",
    imagem: "./img/urso-panda.jpeg",
    dimencoes: "13(A) x 08(L) x 10(C) Cm ",
    categoria: "animais",
  },
  {
    nome: "Urso Panda M",
    preco: "R$ 310,00",
    imagem: "./img/urso-panda.jpeg",
    dimencoes: "26(A) x 23(L) x 21(C) Cm ",
    categoria: "animais",
  },
  {
    nome: "Cachorro deitado",
    preco: "R$ 279,00",
    imagem: "./img/cachorrodeitado.jpg",
    dimencoes: "22(A) x 13(L) x 39(C) Cm ",
    categoria: "animais",
  },
  {
    nome: "Cachorro Labrador",
    preco: "R$ 410,00",
    imagem: "./img/labrador.jpeg",
    dimencoes: "18(A) x 33(L) x 08(C) Cm ",
    categoria: "animais",
  },
  {
    nome: "Jaguar Inclinado P",
    preco: "R$ 277,00",
    imagem: "./img/jaguarInclinadoP.png",
    dimencoes: "36(A) x 24(L) x 15(C) Cm ",
    categoria: "animais",
  },

  {
    nome: "Buldogue P",
    preco: "R$ 210,00",
    imagem: "./img/buldogue.jpeg",
    dimencoes: "14(A) x 13(L) x 15(C) Cm ",
    categoria: "animais",
  },
  {
    nome: "Buldogue PP",
    preco: "R$ 168,00",
    imagem: "./img/buldogue.jpeg",
    dimencoes: "10(A) x 09(L) x 11(C) Cm ",
    categoria: "animais",
  },
  {
    nome: "Gato PP",
    preco: "R$ 168,00",
    imagem: "./img/gatoPP.png",
    dimencoes: "28(A) x 08(L) x 13(C) Cm ",
    categoria: "animais",
  },
  {
    nome: "Leopardo PP",
    preco: "R$ 378,00",
    imagem: "./img/leopardo.jpeg",
    dimencoes: "14(A) x 39(L) x 09(C) Cm ",
    categoria: "animais",
  },
  {
    nome: "Pantera Deitada",
    preco: "R$ 756,00",
    imagem: "./img/pantera-deitada.jpeg",
    dimencoes: "59(A) x 21(L) x 28(C) Cm ",
    categoria: "animais",
  },
  {
    nome: "Leopardo Deitado",
    preco: "R$ 950,00",
    imagem: "./img/leopardoDeitado.png",
    dimencoes: "30(A)x20(L)x78(C) cm ",
    categoria: "animais",
  },
  {
    nome: "Cachorro Galgo G",
    preco: "R$ 2.630,00",
    imagem: "./img/galgo.jpeg",
    dimencoes: "114(A) x 42(L) x 33(C) Cm ",
    categoria: "animais",
  },
  {
    nome: "Cachorro Sentado G",
    preco: "R$ 830,00",
    imagem: "./img/cachorroG.png",
    dimencoes: "60(A)x24(L)x38(C) Cm ",
    categoria: "animais",
  },
  {
    nome: "Cachorro Sentado M",
    preco: "R$ 530,00",
    imagem: "./img/cachorroM.png",
    dimencoes: "42(A)x16(L)x27(C) Cm ",
    categoria: "animais",
  },
  {
    nome: "Cachorro Sentado P",
    preco: "R$ 277,00",
    imagem: "./img/cachorroP.png",
    dimencoes: "25(A)x10(L)x17(C) Cm ",
    categoria: "animais",
  },
  {
    nome: "Cachorro Galgo M",
    preco: "R$ 1.320,00",
    imagem: "./img/galgo.jpeg",
    dimencoes: "75(A) x 32(L) x 24(C) Cm ",
    categoria: "animais",
  },

  {
    nome: "Escultura Lisa",
    preco: "R$ 260,00",
    imagem: "./img/escultura-lisa.jpeg",
    dimencoes: "50(A) x 14(L) x 14(C) Cm ",
    categoria: "esculturas",
  },
  {
    nome: "Escultura Mascara Teatro",
    preco: "R$ 249,00",
    imagem: "./img/escultura-teatro.jpeg",
    dimencoes: "42(A) x 14(L) x 13(C) Cm ",
    categoria: "esculturas",
  },
  {
    nome: "Escultura Mascara Reversa",
    preco: "R$ 279,00",
    imagem: "./img/mascara-reversa.jpeg",
    dimencoes: "42(A) x 14(L) x 13(C) Cm ",
    categoria: "esculturas",
  },
  {
    nome: "Escultura Dragão",
    preco: "R$ 350,00",
    imagem: "./img/escultura-dragao.jpeg",
    dimencoes: "30(A) x 26(L) x 17(C) Cm ",
    categoria: "animais",
  },
  {
    nome: "Tubarão Parede",
    preco: "R$ 390,00",
    imagem: "./img/tubarao.jpeg",
    dimencoes: "00(A) x 00(L) x 00(C) Cm ",
    categoria: "animais",
  },
  {
    nome: "Barco",
    preco: "R$ 199,00",
    imagem: "./img/escultura-barco.jpeg",
    dimencoes: "37(A) x 07(L) x 24(C) Cm ",
    categoria: "esculturas",
  },
  {
    nome: "Busto Pantera",
    preco: "R$ 499,00",
    imagem: "./img/busto-pantera.jpeg",
    dimencoes: "40(A) x 30(L) x 45(C) Cm ",
    categoria: "esculturas",
  },
  {
    nome: "Leão com Base PP",
    preco: "R$ 310,00",
    imagem: "./img/leao-com-base.jpeg",
    dimencoes: "30(A) x 20(L) x 15(C) Cm ",
    categoria: "esculturas",
  },
  {
    nome: "Leão Caminhando PP",
    preco: "R$ 99,00",
    imagem: "./img/leaoPP.png",
    dimencoes: "11(A)x15(L)x05(C) cm ",
    categoria: "animais",
  },
   {
    nome: "Urso Pedestal",
    preco: "R$ 190,00",
    imagem: "./img/ursoPedestal.png",
    dimencoes: "25(A)x15(L)x13(C) Cm ",
    categoria: "animais",
  },
  {
    nome: "Cavalo Raio ",
    preco: "M= R$ 330,00 P= R$ 290,00",
    imagem: "./img/cavaloraio.png",
    dimencoes: "M= 40(A)x08(L)x20(C) Cm <p> P= 30(A)x06(L)x18(C) Cm ",
    categoria: "animais",
  },
  {
    nome: "Garrafa Vintage G",
    preco: "R$ 499,00",
    imagem: "./img/garrafa-flordeliz.jpeg",
    dimencoes: "80(A) x 12(L) x 12(C) Cm ",
    categoria: "garrafas",
  },
  {
    nome: "Garrafa Vintage P",
    preco: "R$ 410,00",
    imagem: "./img/garrafa-flordeliz.jpeg",
    dimencoes: "70(A) x 10(L) x 10(C) Cm ",
    categoria: "garrafas",
  },
  {
    nome: "Garrafa Folhas G",
    preco: "R$ 549,00",
    imagem: "./img/garrafaFolhasG.png",
    dimencoes: "75(A)x15(L)x15(C) Cm",
    categoria: "garrafas",
  },
  {
    nome: "Garrafa Folhas M",
    preco: "R$ 499,00",
    imagem: "./img/garrafaFolhasM.png",
    dimencoes: "60(A)x14(L)x14(C) Cm",
    categoria: "garrafas",
  },

  {
    nome: "Garrafas Listrada G",
    preco: "R$ 275,00",
    imagem: "./img/garrafas-listrada.jpeg",
    dimencoes: "42(A) x 10(L) x 10(C) Cm ",
    categoria: "garrafas",
  },
  {
    nome: "Garrafas Listrada M",
    preco: "R$ 259,00",
    imagem: "./img/garrafas-listrada.jpeg",
    dimencoes: "36(A) x 09(L) x 09(C) Cm ",
    categoria: "garrafas",
  },

  {
    nome: "Garrafas Listrada P",
    preco: "R$ 230,00",
    imagem: "./img/garrafas-listrada.jpeg",
    dimencoes: "30(A) x 09(L) x 09(C) Cm ",
    categoria: "garrafas",
  },

  {
    nome: "Garrafa Treliça G",
    preco: "R$ 455,00",
    imagem: "./img/garrafa-treliçaGjpeg.jpeg",
    dimencoes: "75(A) x 13(L) x 13(C) Cm ",
    categoria: "garrafas",
  },

  {
    nome: "Garrafa Treliça P",
    preco: "R$ 410,00",
    imagem: "./img/garrafa-treliçap.jpeg",
    dimencoes: "66(A) x 13(L) x 13(C) Cm ",
    categoria: "garrafas",
  },

  {
    nome: "Garrafa Quadrada",
    preco: "R$ 410,00",
    imagem: "./img/garrafa-retangulo.jpeg",
    dimencoes: "27(A) x 10(L) x 48(C) Cm ",
    categoria: "garrafas",
  },
  {
    nome: "Garrafa Retângulo",
    preco: "R$ 475,00",
    imagem: "./img/garrafa-quadrada.jpeg",
    dimencoes: "35(A) x 10(L) x 35(C) Cm ",
    categoria: "garrafas",
  },
  {
    nome: "Águia M",
    preco: "R$ 1.110,00",
    imagem: "./img/aguia.jpeg",
    dimencoes: "73(A) x 32(L) x 30(C) Cm ",
    categoria: "animais",
  },
  {
    nome: "Águia P",
    preco: "R$ 830,00",
    imagem: "./img/aguia.jpeg",
    dimencoes: "58(A) x 28(L) x 20(C) Cm ",
    categoria: "animais",
  },
  {
    nome: "Vaso Liso Aberto",
    preco: "R$ 1.100,00",
    imagem: "./img/vaso-flordeliz.jpeg",
    dimencoes: "85(A) x 47(L) Cm ",
    categoria: "vasos",
  },

  {
    nome: "Vaso Irregular P",
    preco: "R$ 820,00",
    imagem: "./img/vaso-irregular.jpeg",
    dimencoes: "80(A) x 30(L) Cm ",
    categoria: "vasos",
  },
  {
    nome: "Vaso Irregular G",
    preco: "R$ 1.090,00",
    imagem: "./img/vaso-irregular.jpeg",
    dimencoes: "100(A) x 40(L) Cm ",
    categoria: "vasos",
  },

  {
    nome: "Vaso Liso P",
    preco: "R$ 670,00",
    imagem: "./img/vaso-liso.jpeg",
    dimencoes: "64(A) x 35(L) Cm ",
    categoria: "vasos",
  },
  {
    nome: "Vaso Liso M",
    preco: "R$ 880,00",
    imagem: "./img/vaso-liso.jpeg",
    dimencoes: "80(A) x 40(L) Cm ",
    categoria: "vasos",
  },
  {
    nome: "Vaso Liso G",
    preco: "R$ 970,00",
    imagem: "./img/vaso-liso.jpeg",
    dimencoes: "91(A) x 40(L) Cm ",
    categoria: "vasos",
  },

  {
    nome: "Vaso Bojudo",
    preco: "R$ 830,00",
    imagem: "./img/vasoBojudo.jpeg",
    dimencoes: "61(A) x 45(L) Cm ",
    categoria: "vasos",
  },
];
